import {
  Bot,
  Box,
  Brain,
  CircuitBoard,
  Cloud,
  CloudCog,
  Code2,
  ContactRound,
  Cpu,
  CreditCard,
  Database,
  GitBranch,
  Globe,
  Layers,
  Layout,
  LayoutGrid,
  type LucideIcon,
  Package,
  Palette,
  Server,
  Share2,
  Smartphone,
  Sparkles,
  TestTube2,
  TrendingUp,
  Users,
  Workflow,
} from 'lucide-react';

/**
 * Map app slugs → Simple Icons CDN slugs.
 * Broken/missing CDN brands are remapped (e.g. reactnative → react) or listed in
 * LOCAL_ONLY_SLUGS so we never request a 404 URL.
 */
export const SLUG_ALIASES: Record<string, string> = {
  adobe: 'sketch',
  adobeillustrator: 'sketch',
  // No dedicated React Native glyph on Simple Icons — use React.
  reactnative: 'react',
  openjdk: 'openjdk',
  rubyonrails: 'rubyonrails',
  vuedotjs: 'vuedotjs',
  nodedotjs: 'nodedotjs',
  nextdotjs: 'nextdotjs',
  postgresql: 'postgresql',
  mongodb: 'mongodb',
  graphql: 'graphql',
  dotnet: 'dotnet',
  angular: 'angular',
  github: 'github',
  trello: 'trello',
  redis: 'redis',
  stripe: 'stripe',
  react: 'react',
  flutter: 'flutter',
  figma: 'figma',
  selenium: 'selenium',
  google: 'google',
  python: 'python',
  android: 'android',
  swift: 'swift',
  laravel: 'laravel',
  instagram: 'instagram',
  pytorch: 'pytorch',
  huggingface: 'huggingface',
  kotlin: 'kotlin',
  terraform: 'terraform',
  jenkins: 'jenkins',
  ansible: 'ansible',
  prometheus: 'prometheus',
  grafana: 'grafana',
  gitlab: 'gitlab',
  tensorflow: 'tensorflow',
  kubernetes: 'kubernetes',
  docker: 'docker',
  zapier: 'zapier',
  n8n: 'n8n',
  langchain: 'langchain',
  typescript: 'typescript',
  tailwindcss: 'tailwindcss',
  firebase: 'firebase',
  wordpress: 'wordpress',
  shopify: 'shopify',
};

/**
 * Brands removed from / blocked on cdn.simpleicons.org — Lucide only.
 * Keep in sync with CDN 404s so we never flash a broken glyph.
 */
export const LOCAL_ONLY_SLUGS = new Set([
  'amazonaws',
  'amazonwebservices',
  'aws',
  'awslambda',
  'azure',
  'chatgpt',
  'grpc',
  'heroku',
  'llamaindex',
  'microsoftazure',
  'openai',
  'anthropic',
  'pinecone',
  'salesforce',
]);

/** Category / capability icons — always Lucide, never brand logos. */
export const SERVICE_ICONS: Record<string, LucideIcon> = {
  erp: Layers,
  crm: ContactRound,
  ai: Brain,
  training: Cpu,
  integration: Bot,
  mlops: CircuitBoard,
  saas: Package,
  custom: Code2,
  mobile: Smartphone,
  web: Globe,
  cloud: Cloud,
  devops: CloudCog,
  automation: Workflow,
  staff: Users,
};

export const FALLBACK_ICONS: Record<string, LucideIcon> = {
  ...SERVICE_ICONS,
  amazonaws: CloudCog,
  amazonwebservices: CloudCog,
  aws: CloudCog,
  awslambda: CloudCog,
  azure: Cloud,
  microsoftazure: Cloud,
  heroku: Cloud,
  salesforce: ContactRound,
  docker: CloudCog,
  adobe: Palette,
  adobeillustrator: Palette,
  sketch: Palette,
  kubernetes: CloudCog,
  openjdk: Code2,
  oracle: Code2,
  java: Code2,
  rubyonrails: Code2,
  ruby: Code2,
  postgresql: Database,
  mongodb: Database,
  graphql: Share2,
  redis: Server,
  trello: LayoutGrid,
  stripe: CreditCard,
  angular: Code2,
  github: GitBranch,
  gitlab: GitBranch,
  jenkins: CloudCog,
  ansible: Server,
  prometheus: TrendingUp,
  grafana: TrendingUp,
  vuedotjs: Code2,
  nodedotjs: Code2,
  nextdotjs: Code2,
  react: Code2,
  reactnative: Code2,
  kotlin: Smartphone,
  terraform: CloudCog,
  tensorflow: Brain,
  dotnet: Code2,
  flutter: Smartphone,
  figma: Layout,
  selenium: TestTube2,
  google: TrendingUp,
  python: Brain,
  android: Smartphone,
  swift: Smartphone,
  laravel: Code2,
  instagram: Share2,
  openai: Sparkles,
  anthropic: Sparkles,
  chatgpt: Sparkles,
  pytorch: Brain,
  huggingface: Brain,
  langchain: Bot,
  langgraph: Workflow,
  llamaindex: Brain,
  pinecone: Database,
  grpc: Share2,
  ollama: Bot,
  pydantic: Code2,
  fastapi: Code2,
  nestjs: Code2,
  django: Code2,
  apachespark: CircuitBoard,
  snowflake: Database,
  openapiinitiative: Code2,
  apachekafka: Workflow,
  rabbitmq: Workflow,
  typescript: Code2,
  tailwindcss: Palette,
  firebase: Server,
  wordpress: Globe,
  shopify: CreditCard,
  zapier: Workflow,
  n8n: Workflow,
};

export function resolveSlug(slug: string) {
  return SLUG_ALIASES[slug] ?? slug;
}

export function resolveFallbackIcon(slug: string, fallbackSlug?: string): LucideIcon {
  const resolved = resolveSlug(slug);
  return (
    FALLBACK_ICONS[slug] ??
    FALLBACK_ICONS[resolved] ??
    (fallbackSlug ? (SERVICE_ICONS[fallbackSlug] ?? FALLBACK_ICONS[fallbackSlug]) : undefined) ??
    Box
  );
}
