export enum JobType {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  CONTRACT = 'CONTRACT',
  INTERNSHIP = 'INTERNSHIP',
}

export enum WorkMode {
  ONSITE = 'ONSITE',
  REMOTE = 'REMOTE',
  HYBRID = 'HYBRID',
}

export enum Department {
  ENGINEERING = 'ENGINEERING',
  DATA_AND_AI = 'DATA_AND_AI',
  HUMAN_RESOURCES = 'HUMAN_RESOURCES',
  DESIGN = 'DESIGN',
}

export enum Designation {
  ASSOCIATE_ENGINEER = 'ASSOCIATE_ENGINEER',
  SENIOR_ENGINEER = 'SENIOR_ENGINEER',
  TEAM_LEAD = 'TEAM_LEAD',
  EXECUTIVE = 'EXECUTIVE',
}
